# encoding: utf8mb4

default: &default
  database: reddevil
  adapter: mysql2
  encoding: utf8
  host: localhost

development:
  <<: *default
  username: <%= Rails.application.credentials.db_dev_user %>
  password: <%= Rails.application.credentials.db_dev_pass %>

test:
  <<: *default
  database: reddevil_test
  username: <%= Rails.application.credentials.db_test_user %>
  password: <%= Rails.application.credentials.db_test_pass %>

production:
  <<: *default
  username: <%= Rails.application.credentials.db_prod_user %>
  password: <%= Rails.application.credentials.db_prod_pass %>
