# encoding: utf8mb4

default: &default
  database: reddevil
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password:

development:
  <<: *default

test:
  <<: *default
  database: reddevil_test

production:
  <<: *default
  database: reddevil
  username: <%= Rails.application.credentials.db_prod_user %>
  password: <%= Rails.application.credentials.db_prod_pass %>
